name: HuskSync
version: ${version}-topeestla
main: net.william278.husksync.BukkitHuskSync
api-version: 1.16
author: William278
description: 'A modern, cross-server player data synchronization system'
website: 'https://william278.net'
softdepend:
  - MysqlPlayerDataBridge
  - Plan
libraries:
  - 'mysql:mysql-connector-java:${mysql_driver_version}'
  - 'org.xerial.snappy:snappy-java:${snappy_version}'
  - 'org.apache.commons:commons-text:${commons_text_version}'
  - 'io.lettuce:lettuce-core:${lettuce_version}'
commands:
  husksync:
    usage: '/husksync <update/info/reload/migrate>'
    description: 'Manage the HuskSync plugin'
  userdata:
    usage: '/userdata <view/list/delete/restore/pin/dump> <username> [version_uuid]'
    description: 'View, manage & restore player userdata'
  inventory:
    usage: '/inventory <username> [version_uuid]'
    description: 'View & edit a player''s inventory'
  enderchest:
    usage: '/enderchest <username> [version_uuid]'
    description: 'View & edit a player''s Ender Chest'